"""
The source PDF extraction dropped every Romanian diacritic character
(ă, â, î, ș, ț), collapsing it to nothing/whitespace. This restores the
highest-frequency recurring liturgical vocabulary via whole-word/phrase
dictionary replacement. It is a best-effort pass over common structural
words, not a full proofread of every rare personal/place name.
"""
import re

# Ordered longest-phrase-first so longer matches win before shorter substrings.
REPLACEMENTS = [
    # High-frequency word-level fixes that must run BEFORE the blanket " i " -> " și "
    # rule below, since these words also contain a lone " i " from an unrelated
    # dropped diacritic (frați, săi) and would otherwise be misread as "și".
    ("fra i", "frați"),
    ("M rturisitor ", "Mărturisitor "),
    ("Neam ;", "Neamț;"),
    ("Neam ,", "Neamț,"),
    ("Râ ca", "Râșca"),
    ("în racl", "în raclă"),
    ("ai s i", "ai săi"),
    ("Înainte- pr znuirea", "Înainte-prăznuirea"),
    ("Înainte-pr znuirea", "Înainte-prăznuirea"),
    ("pr znuirea", "prăznuirea"),
    ("împreun cu", "împreună cu"),
    (" tefan", " Ștefan"),
    ("M rt.", "Mărt."),
    ("p timit", "pătimit"),
    ("Lauren iu", "Laurențiu"),
    ("V ratec", "Văratec"),
    ("Sfin i i Mc.", "Sfințiți Mucenici"),
    ("dup Rusalii", "după Rusalii"),
    ("dup Pa ti", "după Paști"),
    ("dup Botezul Domnului", "după Botezul Domnului"),
    ("dinaintea Botezului Domnului", "dinaintea Botezului Domnului"),
    ("Duminica dinaintea", "Duminica dinaintea"),
    ("Sfin ii Trei Ierarhi", "Sfinții Trei Ierarhi"),
    ("Sfin ii Mari Împ ra i", "Sfinții Mari Împărați"),
    ("Sfin ii P rin i", "Sfinții Părinți"),
    ("Sfin ii 40", "Sfinții 40"),
    ("Sfin ii 33", "Sfinții 33"),
    ("Sfin ii 26", "Sfinții 26"),
    ("Sfin ii 20.000", "Sfinții 20.000"),
    ("Sfin ii 14.000", "Sfinții 14.000"),
    ("Sfin ii 70", "Sfinții 70"),
    ("Sfin ii 45", "Sfinții 45"),
    ("Sfin ii 10", "Sfinții 10"),
    ("Sfin i i Mc.", "Sfinții Mucenici"),
    ("Sf. Sfin it Mc.", "Sf. Sfințit Mucenic"),
    ("Sf. Sfin i i Mc.", "Sf. Sfinții Mucenici"),
    ("Sf. Cuv. Mc.", "Sf. Cuvioasa Muceniță"),
    ("Sf. Mare Mc.", "Sf. Mare Mucenic"),
    ("Sf. Mari Mc.", "Sf. Marii Mucenici"),
    ("Sf. Mc.", "Sf. Mucenic"),
    ("Sf. Cuv.", "Sf. Cuvios"),
    ("Sf. Ap. i Ev.", "Sf. Ap. și Ev."),
    ("Sf. Ap. i Evanghelist", "Sf. Apostol și Evanghelist"),
    ("Sf. Ier.", "Sf. Ierarh"),
    ("Sf. Proroc", "Sf. Proroc"),
    ("Sf. Drep ii", "Sf. Drepții"),
    ("Sf. i Dreptul", "Sf. și Dreptul"),
    ("Sf. i Drep ii", "Sf. și Drepții"),
    ("Sfânta i Marea", "Sfânta și Marea"),
    ("praznicului Na terii Domnului", "praznicului Nașterii Domnului"),
    ("Na terea Domnului", "Nașterea Domnului"),
    ("Na terea Maicii Domnului", "Nașterea Maicii Domnului"),
    ("Na terea Sf. Proroc Ioan Botez torul", "Nașterea Sf. Proroc Ioan Botezătorul"),
    ("T ierea-împrejur", "Tăierea-împrejur"),
    ("T ierea capului", "Tăierea capului"),
    ("Ioan Botez torul", "Ioan Botezătorul"),
    ("Botez torul", "Botezătorul"),
    ("Botezul Domnului", "Botezul Domnului"),
    ("Adormirea Maicii Domnului", "Adormirea Maicii Domnului"),
    ("Adormirea Sfintei Ana", "Adormirea Sfintei Ana"),
    ("Schimbarea la Fa a Domnului", "Schimbarea la Față a Domnului"),
    ("Schimb rii la Fa a Domnului", "Schimbării la Față a Domnului"),
    ("În l area Domnului", "Înălțarea Domnului"),
    ("În l area Sfintei Cruci", "Înălțarea Sfintei Cruci"),
    ("În l rii Domnului", "Înălțării Domnului"),
    ("În l rii Sfintei Cruci", "Înălțării Sfintei Cruci"),
    ("Aflarea Sfintei Cruci", "Aflarea Sfintei Cruci"),
    ("Aducerea moa telor", "Aducerea moaștelor"),
    ("Mutarea moa telor", "Mutarea moaștelor"),
    ("Intrarea Domnului în Ierusalim", "Intrarea Domnului în Ierusalim"),
    ("Intrarea în biseric a Maicii Domnului", "Intrarea în biserică a Maicii Domnului"),
    ("Întâmpinarea Domnului", "Întâmpinarea Domnului"),
    ("Întâmpin rii Domnului", "Întâmpinării Domnului"),
    ("Buna Vestire", "Buna Vestire"),
    ("Bunei Vestiri", "Bunei Vestiri"),
    ("Pogorârea Sfântului Duh", "Pogorârea Sfântului Duh"),
    ("Pogorârii Sfântului Duh", "Pogorârii Sfântului Duh"),
    ("Sfânta Treime", "Sfânta Treime"),
    ("Sfintele Pa ti", "Sfintele Paști"),
    ("Sfânta Cruce", "Sfânta Cruce"),
    ("Sfintei Cruci", "Sfintei Cruci"),
    ("Duminica Sfintei Învieri", "Duminica Sfintei Învieri"),
    ("Învierea Domnului", "Învierea Domnului"),
    ("Odovania praznicului", "Odovania praznicului"),
    ("Odovania Postului", "Odovania Postului"),
    ("Odovania Înjum t irii Cincizecimii", "Odovania Înjumătățirii Cincizecimii"),
    ("Înjum t irea Cincizecimii", "Înjumătățirea Cincizecimii"),
    ("Începutul Postului", "Începutul Postului"),
    ("Începutul anului bisericesc", "Începutul anului bisericesc"),
    ("Începutul Triodului", "Începutul Triodului"),
    ("L satul secului", "Lăsatul secului"),
    ("l satul secului", "lăsatul secului"),
    ("Ajunul Botezului Domnului", "Ajunul Botezului Domnului"),
    ("Ajunul Cr ciunului", "Ajunul Crăciunului"),
    ("Cr ciunul", "Crăciunul"),
    ("Cr ciun", "Crăciun"),
    ("Zi aliturgic", "Zi aliturgică"),
    ("zile aliturgice", "zile aliturgice"),
    ("Sâmb ta mor ilor", "Sâmbăta morților"),
    ("Sâmb ta lui Laz r", "Sâmbăta lui Lazăr"),
    ("Sâmb ta Sfin ilor Cuvio i", "Sâmbăta Sfinților Cuvioși"),
    ("Sâmb ta Sf. Mare", "Sâmbăta Sf. Mare"),
    ("Pomenirea celor adormi i", "Pomenirea celor adormiți"),
    ("Mo ii de iarn", "Moșii de iarnă"),
    ("Mo ii de var", "Moșii de vară"),
    ("Mo ii de toamn", "Moșii de toamnă"),
    ("Predica Sfântului Ioan Botez torul", "Predica Sfântului Ioan Botezătorul"),
    ("Predica de pe munte", "Predica de pe munte"),
    ("Rug ciunea lui Iisus", "Rugăciunea lui Iisus"),
    ("Vindecarea sl b nogului", "Vindecarea slăbănogului"),
    ("Vindecarea celor doi", "Vindecarea celor doi"),
    ("Vindecarea a doi orbi", "Vindecarea a doi orbi"),
    ("Vindecarea lunaticului", "Vindecarea lunaticului"),
    ("Vindecarea fiului lunatic", "Vindecarea fiului lunatic"),
    ("Vindecarea orbului din na tere", "Vindecarea orbului din naștere"),
    ("Vindecarea demonizatului", "Vindecarea demonizatului"),
    ("Vindecarea slugii suta ului", "Vindecarea slugii sutașului"),
    ("Cererea fiilor lui Zevedeu", "Cererea fiilor lui Zevedeu"),
    ("Pilda", "Pilda"),
    ("Chemarea lui Filip i a lui Natanael", "Chemarea lui Filip și a lui Natanael"),
    ("Chemarea primilor Apostoli", "Chemarea primilor Apostoli"),
    ("Luarea crucii i urmarea lui Hristos", "Luarea crucii și urmarea lui Hristos"),
    ("Urmarea lui Hristos", "Urmarea lui Hristos"),
    ("Iubirea vr jma ilor", "Iubirea vrăjmașilor"),
    ("Genealogia Mântuitorului", "Genealogia Mântuitorului"),
    ("Fuga în Egipt", "Fuga în Egipt"),
    ("Potolirea furtunii", "Potolirea furtunii"),
    ("Pescuirea minunat", "Pescuirea minunată"),
    ("Înmul irea pâinilor", "Înmulțirea pâinilor"),
    ("Convorbirea lui Iisus cu Nicodim", "Convorbirea lui Iisus cu Nicodim"),
    ("Înv tur despre iertare, post i neagonisire", "Învățătură despre iertare, post și neagonisire"),
    ("Despre grijile vie ii", "Despre grijile vieții"),
    ("Duminica Izgonirii lui Adam din Rai", "Duminica Izgonirii lui Adam din Rai"),
    ("Duminica Înfrico toarei Judec i", "Duminica Înfricoșătoarei Judecăți"),
    ("a L satului sec de carne", "a Lăsatului sec de carne"),
    ("a L satului sec de brânz", "a Lăsatului sec de brânză"),
    ("a Întoarcerii Fiului risipitor", "a Întoarcerii Fiului risipitor"),
    ("dumnezeie ti P rin i", "dumnezeiești Părinți"),
    ("Drepta Elisabeta", "Drepta Elisabeta"),
    ("p rin ii Sf. Ioan Botez torul", "părinții Sf. Ioan Botezătorul"),
    ("Z mislirea", "Zămislirea"),
    ("A ezarea", "Așezarea"),
    ("A ezarea ve mântului", "Așezarea veșmântului"),
    ("N sc toarei de Dumnezeu", "Născătoarei de Dumnezeu"),
    ("Preasfintei N sc toare de Dumnezeu", "Preasfintei Născătoare de Dumnezeu"),
    ("Maicii Domnului", "Maicii Domnului"),
    ("cinstitului brâu", "cinstitului brâu"),
    ("Soborul Sf.", "Soborul Sf."),
    ("Soborul Sfin ilor", "Soborul Sfinților"),
    ("Soborul Sfintelor Femei Românce", "Soborul Sfintelor Femei Românce"),
    ("Soborul Maicii Domnului", "Soborul Maicii Domnului"),
    ("Sf. Arhanghel Gavriil", "Sf. Arhanghel Gavriil"),
    ("Sf. Arhangheli Mihail i Gavriil", "Sf. Arhangheli Mihail și Gavriil"),
    ("Împ ra i", "Împărați"),
    ("Împ ratul", "Împăratul"),
    ("împ ratul", "împăratul"),
    ("împ rat", "împărat"),
    ("Împ r teasa", "Împărăteasa"),
    ("împ r teasa", "împărăteasa"),
    ("cel întocmai cu Apostolii", "cel întocmai cu Apostolii"),
    ("cea întocmai cu Apostolii", "cea întocmai cu Apostolii"),
    ("întocmai cu Apostolii", "întocmai cu Apostolii"),
    ("primul episcop sârb", "primul episcop sârb"),
    ("Ierarhul", "Ierarhul"),
    ("mitropolitul", "mitropolitul"),
    ("mitropolitul Moldovei", "mitropolitul Moldovei"),
    ("arhiepiscopul", "arhiepiscopul"),
    ("arhiepiscopii", "arhiepiscopii"),
    ("patriarhul", "patriarhul"),
    ("patriarhii", "patriarhii"),
    ("episcopul", "episcopul"),
    ("episcopi", "episcopi"),
    ("M rturisitorul", "Mărturisitorul"),
    ("M rturisitoarea", "Mărturisitoarea"),
    ("M rturisitoare", "Mărturisitoare"),
    ("m rturisitorul", "mărturisitorul"),
    ("M rturisitori", "Mărturisitori"),
    ("f c torul de minuni", "făcătorul de minuni"),
    ("f c toarea de minuni", "făcătoarea de minuni"),
    ("primitorul de Dumnezeu", "primitorul de Dumnezeu"),
    ("primitorul de str ini", "primitorul de străini"),
    ("Cel Sfin it", "cel Sfințit"),
    ("cel Sfin it", "cel sfințit"),
    ("cel Nou", "cel Nou"),
    ("cel Mare", "cel Mare"),
    ("cea Mare", "cea Mare"),
    ("cel B trân", "cel Bătrân"),
    ("lumin torul", "luminătorul"),
    ("Lumin torul", "Luminătorul"),
    ("lumin toarea", "luminătoarea"),
    ("Doctorii f r de argin i", "Doctorii fără de arginți"),
    ("doctori f r de argin i", "doctori fără de arginți"),
    ("f r de argin i", "fără de arginți"),
    ("prin cei 70", "din cei 70"),
    ("din cei 70", "din cei 70"),
    ("de la Sinodul al", "de la Sinodul al"),
    ("Sinodul I Ecumenic", "Sinodul I Ecumenic"),
    ("lea Ecumenic", "-lea Ecumenic"),
    ("Ap rin i", "Ap. Părinți"),
    ("P rin i", "Părinți"),
    ("p rin i", "părinți"),
    ("din inutul", "din ținutul"),
    ("inutul", "ținutul"),
    ("i sora sa", "și sora sa"),
    ("i fra ii s i", "și frații săi"),
    ("i fiii ei", "și fiii ei"),
    ("i fiii lor", "și fiii lor"),
    ("cu fiii ei", "cu fiii ei"),
    ("so ia sa", "soția sa"),
    ("so ia", "soția"),
    ("nepoata sa", "nepoata sa"),
    ("mama sa", "mama sa"),
    ("fiica împ ratului", "fiica împăratului"),
    ("din Persia", "din Persia"),
    ("Vasile cel Mare", "Vasile cel Mare"),
    ("Grigorie Teologul", "Grigorie Teologul"),
    ("Ioan Gur de Aur", "Ioan Gură de Aur"),
    ("Gur de Aur", "Gură de Aur"),
    ("Sfin ii", "Sfinții"),
    ("sfin ii", "sfinții"),
    ("Sfin ilor", "Sfinților"),
    ("sfin ilor", "sfinților"),
    ("Sf n nt", "Sfânt"),
    (" i ", " și "),
    (" i,", " și,"),
    (" i;", " și;"),
    (" i.", " și."),
    (" i-", " și-"),
    ("dup ", "după "),
    ("dup;", "după;"),
    ("dup.", "după."),
    ("i-a", "i-a"),
]


def restore_diacritics_ro(text):
    for broken, fixed in REPLACEMENTS:
        text = text.replace(broken, fixed)
    text = re.sub(r"\s+", " ", text).strip()
    return text
